export const GET_CONTACTS_SUCCESS="GET_CONTACTS_SUCCESS"
export const GET_CONTACT_SUCCESS="GET_CONTACT_SUCCESS"
export const GET_CONTACTS_LOAD="GET_CONTACTS_LOAD"
export const GET_CONTACTS_FAIL="GET_CONTACTS_FAIL"